import fs from 'node:fs';
import { buildGrid, seedOrders, replacementFor } from './grid.js';
import { PaperExchange } from './paper.js';
import { PopdexLiveExchange } from './popdex-live.js';
function loadEnv(){if(fs.existsSync('.env'))for(const line of fs.readFileSync('.env','utf8').split(/\r?\n/)){const m=line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2].replace(/^['"]|['"]$/g,'');}}
const n=(key,fallback)=>Number(process.env[key]??fallback); loadEnv();
const config={mode:(process.env.MODE||'paper').toLowerCase(),lower:n('LOWER',90000),upper:n('UPPER',110000),gridCount:n('GRID_COUNT',20),sizeBase:n('ORDER_SIZE_BASE',.001),gridMode:process.env.GRID_MODE||'neutral',skipBand:n('SKIP_BAND',.25),pollMs:n('POLL_MS',1500)};
if(!['paper','live'].includes(config.mode)||!['neutral','long','short'].includes(config.gridMode))throw Error('MODE or GRID_MODE invalid');
function buildTickerUrl(){const base=(process.env.POPDEX_API_BASE||'https://api.popdex.xyz').replace(/\/$/,'');const path=process.env.POPDEX_TICKER_PATH||'/api/v1/public/market/tickers';const qs=new URLSearchParams({category:process.env.POPDEX_API_CATEGORY||'Futures',symbol:process.env.POPDEX_SYMBOL||''});return `${base}${path}?${qs}`;}
const live={rpcUrl:process.env.POPDEX_RPC_URL,agentPrivateKey:process.env.POPDEX_AGENT_PRIVATE_KEY,mainAccount:process.env.POPDEX_MAIN_ACCOUNT,orderContract:process.env.POPDEX_ORDER_CONTRACT,symbolId:n('POPDEX_SYMBOL_ID',0),category:n('POPDEX_CATEGORY',0),positionSide:n('POPDEX_POSITION_SIDE',0),tickerUrl:process.env.POPDEX_TICKER_URL||buildTickerUrl(),tickerJsonPath:process.env.POPDEX_TICKER_JSON_PATH||'data.0.lastPrice'};
const exchange=config.mode==='live'?new PopdexLiveExchange(live):new PaperExchange({price:n('PAPER_START_PRICE',100000),balance:n('PAPER_BALANCE',10000),feeRate:n('FEE_RATE',.0005),volatility:n('PAPER_VOLATILITY',.002)});
const grid=buildGrid(config),active=new Map();
async function place(o){const r=await exchange.placeOrder({...o,sizeBase:config.sizeBase});active.set(r.id,o);console.log(`PLACE ${o.side.toUpperCase()} level=${o.levelIndex} price=${o.price} reduceOnly=${o.reduceOnly} id=${r.id}`);}
const startPrice=await exchange.getPrice();console.log(`PopDEX grid starting: ${config.mode}, ${config.gridMode}, price=${startPrice}, range=${config.lower}-${config.upper}, cells=${config.gridCount}`);for(const o of seedOrders({...grid,price:startPrice,mode:config.gridMode,skipBand:config.skipBand}))await place(o);
if(config.mode==='paper'){exchange.on('fill',async fill=>{console.log(`FILL ${fill.side.toUpperCase()} ${fill.sizeBase}@${fill.price}`);const next=replacementFor(fill,grid.levels,config.gridMode);if(next)await place(next);});setInterval(()=>exchange.tick(),config.pollMs);setInterval(()=>console.log(`STATUS price=${exchange.price.toFixed(2)} active=${active.size} pos=${exchange.position.size} balance=${exchange.balance.toFixed(2)}`),10000);}else console.log('Live orders seeded. This minimal version intentionally does not reconcile on-chain fills yet; stop it before changing configuration.');
