import { Interface, JsonRpcProvider, Wallet, ZeroAddress, encodeBytes32String, parseUnits } from 'ethers';
import { attachLiveReconciliation } from './live-reconcile.js';
const ABI=['function placeOrder(address account,bytes32 clientOrderId,uint16 symbolId,bytes32 orderParams,uint256 price,uint256 qty,uint256 slippage,address builder,uint256 builderFeeRate) returns (bool)'];
const ORDER_IFACE=new Interface(ABI);
const ORDER_PRECOMPILE='0x0000000000000000000000000000000000001000';
// PopDEX Agent accounts cannot be used as EVM transaction senders. The Agent
// signs the calldata, while the delegated main account must be the sender.
const SEND_ABI=['function execute(address agent,bytes data)'];
function paramsFor(o,c){const b=Buffer.alloc(32);b[0]=Number(c.category);b[1]=0;b[2]=o.side==='buy'?0:1;b[3]=1;b[4]=0;b[5]=0;b[6]=o.reduceOnly?1:0;b[7]=Number(c.positionSide);b[8]=0;b[9]=0;return '0x'+b.toString('hex');}
export class PopdexLiveExchange { constructor(c){this.c=c;for(const k of ['rpcUrl','agentPrivateKey','mainAccount','orderContract','symbolId','tickerUrl','tickerJsonPath'])if(c[k]===undefined||c[k]==='')throw new Error(`Live mode requires ${k}`);this.provider=new JsonRpcProvider(c.rpcUrl,2184,{staticNetwork:true});this.wallet=new Wallet(c.agentPrivateKey);this.cancelIface=new Interface(['function cancelOrder(address account,uint128 orderId,bytes32 clientOrderId)']);this.orderContract=ORDER_PRECOMPILE;this.walletAddress=this.wallet.address;if(this.walletAddress.toLowerCase()===this.c.mainAccount.toLowerCase())throw new Error('Agent 不能与主账户相同');} async getPrice(){const r=await fetch(this.c.tickerUrl,{signal:AbortSignal.timeout(8000)});if(!r.ok)throw Error(`Ticker HTTP ${r.status}`);let v=await r.json();for(const key of this.c.tickerJsonPath.split('.'))v=v?.[key];const p=Number(v);if(!(p>0))throw Error('Ticker value is not a positive number');return p} async placeOrder(o){const lot=Number(this.c.lotSize||0.0001);const rawSize=Number(o.sizeBase);const sizeBase=lot>0?Math.floor((rawSize+1e-12)/lot)*lot:rawSize;if(!(sizeBase>0))throw Error(`订单数量 ${rawSize} 小于最小数量或不是最小变动单位 ${lot}`);const params=paramsFor(o,this.c);const clientOrderId=encodeBytes32String(`grid-${Date.now()}-${Math.floor(Math.random()*1e6)}`.slice(0,31));const data=ORDER_IFACE.encodeFunctionData('placeOrder',[this.c.mainAccount,clientOrderId,this.c.symbolId,params,parseUnits(String(o.price),18),parseUnits(sizeBase.toFixed(8),18),0,ZeroAddress,0]);const raw=await this.wallet.signTransaction({to:ORDER_PRECOMPILE,data,nonce:Date.now(),gas:1000000,gasPrice:0,type:0,chainId:2184});const rpc=await fetch(this.c.rpcUrl,{method:'POST',headers:{'content-type':'application/json','Origin':'https://app.popdex.xyz','Referer':'https://app.popdex.xyz/'},body:JSON.stringify({jsonrpc:'2.0',method:'eth_sendRawTransaction',params:[raw],id:String(Date.now())}),signal:AbortSignal.timeout(15000)});const body=await rpc.text();let result;try{result=JSON.parse(body)}catch{throw Error(`RPC 返回非 JSON：${body}`)}if(!rpc.ok||result.error||!result.result)throw Error(`PopDEX eth_sendRawTransaction 失败：${body}`);const txHash=result.result;await this.waitReceipt(txHash);return{id:txHash,txHash,receiptStatus:'confirmed',sizeBase}} }
attachLiveReconciliation(PopdexLiveExchange);
