import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildGrid, seedOrders, replacementFor } from './grid.js';
import { PopdexLiveExchange } from './popdex-live.js';
import { sendTelegram } from './telegram.js';

export class GridRunner {
  constructor(env) { this.env=env; this.stateFile=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..','.runtime-state.json'); this.running=false; this.active=new Map(); this.officialOrders=[]; this.fills=[]; this.seenFills=new Set(); this.log=[]; this.timer=null; this.reconcileBusy=false; this.exchange=null; this.config=null; this.grid=null; this.lastPrice=null; this.startedAt=null; this.error=null; this.manualStop=false; this.settings=this.makeSettings(); this.restoreState(); }
  _n(k,d){return Number(this.env[k]??d)}
  makeSettings(overrides={}) { const s={mode:'live',lower:this._n('LOWER',90000),upper:this._n('UPPER',110000),gridCount:this._n('GRID_COUNT',20),sizeBase:this._n('ORDER_SIZE_BASE',.0002),lotSize:this._n('POPDEX_LOT_SIZE',.0002),gridMode:this.env.GRID_MODE||'neutral',leverage:this._n('LEVERAGE',1),skipBand:this._n('SKIP_BAND',.25),pollMs:this._n('POLL_MS',1500),apiBase:this.env.POPDEX_API_BASE||'https://api.popdex.xyz',tickerPath:this.env.POPDEX_TICKER_PATH||'/api/v1/public/market/tickers',tickerJsonPath:this.env.POPDEX_TICKER_JSON_PATH||'data.0.lastPrice',apiCategory:this.env.POPDEX_API_CATEGORY||'Futures',symbol:this.env.POPDEX_SYMBOL||'',rpcUrl:this.env.POPDEX_RPC_URL||'https://app.popdex.xyz/api/v1/web3/rpc',agentPrivateKey:this.env.POPDEX_AGENT_PRIVATE_KEY||'',mainAccount:this.env.POPDEX_MAIN_ACCOUNT||'',orderContract:this.env.POPDEX_ORDER_CONTRACT||'0x0000000000000000000000000000000000001000',symbolId:this.env.POPDEX_SYMBOL_ID||'20000',category:this.env.POPDEX_CATEGORY||'2',positionSide:this.env.POPDEX_POSITION_SIDE||'0',apiToken:this.env.POPDEX_API_TOKEN||'',tickSize:this._n('POPDEX_TICK_SIZE',0),...overrides,mode:'live'}; for(const k of ['lower','upper','gridCount','sizeBase','lotSize','skipBand','pollMs','leverage','tickSize'])s[k]=Number(s[k]); return s; }
  validateSettings(s, requireLive=true){if(s.mode!=='live')throw Error('本脚本仅支持实盘 MODE=live');if(!['neutral','long','short'].includes(s.gridMode))throw Error('网格模式无效');buildGrid(s);if(!(s.sizeBase>0))throw Error('每格数量必须大于 0');if(requireLive){for(const k of ['symbol','rpcUrl','agentPrivateKey','mainAccount','orderContract','symbolId','category','positionSide'])if(s[k]===undefined||s[k]===null||String(s[k]).trim()==='')throw Error(`主网配置缺少：${k}`);}}
  _persist() { const data={version:1,manualStop:this.manualStop,running:this.running,settings:{...this.settings,agentPrivateKey:undefined,apiToken:undefined},config:this.config,lastPrice:this.lastPrice,startedAt:this.startedAt,active:[...this.active.values()],officialOrders:this.officialOrders,fills:this.fills,seenFills:[...this.seenFills],log:this.log.slice(0,80)}; try { fs.writeFileSync(this.stateFile,JSON.stringify(data,null,2),'utf8'); } catch(e) { this.error=`状态保存失败：${e.message}`; } }
  restoreState() { try { if(!fs.existsSync(this.stateFile)) return; const d=JSON.parse(fs.readFileSync(this.stateFile,'utf8')); if(d.settings) this.settings=this.makeSettings(d.settings); this.manualStop=!!d.manualStop; this.config=d.config||null; this.lastPrice=d.lastPrice??null; this.startedAt=d.startedAt??null; this.officialOrders=Array.isArray(d.officialOrders)?d.officialOrders:[]; this.fills=Array.isArray(d.fills)?d.fills:[]; this.seenFills=new Set(Array.isArray(d.seenFills)?d.seenFills:[]); this.log=Array.isArray(d.log)?d.log:[]; if(this.config)this.grid=buildGrid(this.config); } catch(e) { this.error=`状态恢复失败：${e.message}`; } }
  _restoreExchange() { const s=this.settings; this.exchange=new PopdexLiveExchange({rpcUrl:s.rpcUrl,agentPrivateKey:s.agentPrivateKey,mainAccount:s.mainAccount,orderContract:s.orderContract,symbolId:Number(s.symbolId),category:Number(s.category),positionSide:Number(s.positionSide),tickerUrl:this.tickerUrl(s),tickerJsonPath:s.tickerJsonPath,apiToken:s.apiToken,symbol:s.symbol,lotSize:s.lotSize}); }
  _derivePosition(fills, price) { let qty=0, avg=0, realized=0; for(const f of fills||[]) { const side=String(f.side||f.orderSide||'').toLowerCase().includes('sell')?-1:1; const q=Number(f.execQty||f.qty||f.quantity||f.size||f.orderQty||0), p=Number(f.execPrice||f.price||f.orderPrice||f.avgPrice||0); if(!(q>0&&p>0)) continue; if(qty===0 || Math.sign(qty)===side) { const n=Math.abs(qty)+q; avg=(Math.abs(qty)*avg+q*p)/n; qty+=side*q; } else { const close=Math.min(Math.abs(qty),q); realized += (qty>0 ? (p-avg) : (avg-p))*close; const left=q-close; qty += side*close; if(left>0){qty=side*left;avg=p;} } } if(!qty)return null; const unrealized=(qty>0?(Number(price)-avg):(avg-Number(price)))*Math.abs(qty); return {sizeBase:qty,entryPrice:avg,unrealizedPnl:unrealized,realizedPnl:realized,source:'derived-from-official-fills',warning:'由官方成交记录推导；待接入 PopDEX 官方持仓接口后替换为官方仓位数据'}; }
  _refreshDerivedPosition() { if(this.config?.mode==='live' && this.lastPrice) this.position=this._derivePosition(this.fills,this.lastPrice); }
  _notify(text) { sendTelegram(text,this.env).catch(e=>this._event(`Telegram 推送失败：${e.message}`)); }
  async resumeExisting() { if(this.manualStop||this.running||this.settings.mode!=='live'||!this.config)return this.state(); this.validateSettings(this.settings); this._restoreExchange(); const r=await this.exchange.reconcile(); if(!r.open.length){this._event('重启恢复检查：官方无未成交挂单，保持未运行。');this._persist();return this.state();} this.officialOrders=r.open; this.running=true; this.manualStop=false; this._event(`重启自动恢复：接管官方网格 ${r.open.length} 笔，不重新下单。`); await this.reconcileLive(); this.timer=setInterval(()=>this.tick().catch(e=>this.fail(e)),this.settings.pollMs); this.timer.unref?.(); this._persist(); return this.state(); }
  async adoptExisting() { if(this.settings.mode!=='live')throw Error('仅实盘支持接管现有官方网格'); if(this.running) return this.state(); this.validateSettings(this.settings); this._restoreExchange(); const r=await this.exchange.reconcile(); if(!r.open.length)throw Error('官方当前没有可接管的未成交挂单'); this.officialOrders=r.open; this.active.clear(); this.running=true; this.manualStop=false; this.error=null; this.lastPrice=await this.exchange.getPrice(); this._event(`手动接管官方网格：${r.open.length} 笔，不重新下单、不撤单。`); await this.reconcileLive(); this.timer=setInterval(()=>this.tick().catch(e=>this.fail(e)),this.settings.pollMs); this.timer.unref?.(); this._persist(); return this.state(); }
  async reconnect() { this._restoreExchange(); const r=await this.exchange.reconcile(); this.officialOrders=r.open; this.lastPrice=await this.exchange.getPrice(); this.error=null; this._event(`交易所已重连并完成只读对账：${r.open.length} 笔官方挂单，未撤单、未平仓、未补单。`); this._persist(); return this.state(); }
  resetStats() { this.error=null; this._event('统计重置请求已记录：保留成交记录、持仓推导和官方挂单，未清除交易数据。'); this._persist(); return this.state(); }
  tickerUrl(s){const base=s.apiBase.replace(/\/$/,'');const qs=new URLSearchParams({category:s.apiCategory,symbol:s.symbol});return `${base}${s.tickerPath}?${qs}`;}
  update(overrides={}){if(this.running)throw Error('运行中不可修改配置；请先停止程序');const next=this.makeSettings({...this.settings,...overrides});this.validateSettings(next,false);this.settings=next;this.error=null;this.manualStop=false;this._event('配置已保存，策略尚未启动。');this._persist();return this.state();}  async start(overrides={}){if(this.running)throw Error('网格已经在运行');if(Object.keys(overrides).length)this.update(overrides);const s=this.settings;this.validateSettings(s);if(s.mode==='live'&&s.lotSize>0)s.sizeBase=Number((Math.floor((s.sizeBase+1e-12)/s.lotSize)*s.lotSize).toFixed(8));if(!(s.sizeBase>0))throw Error(`每格数量必须至少为 ${s.lotSize}`);this.config={lower:s.lower,upper:s.upper,gridCount:s.gridCount,sizeBase:s.sizeBase,leverage:s.leverage,gridMode:s.gridMode,skipBand:s.skipBand,pollMs:s.pollMs,tickSize:s.tickSize,mode:s.mode};this.grid=buildGrid(this.config);this.exchange=new PopdexLiveExchange({rpcUrl:s.rpcUrl,agentPrivateKey:s.agentPrivateKey,mainAccount:s.mainAccount,orderContract:s.orderContract,symbolId:Number(s.symbolId),category:Number(s.category),positionSide:Number(s.positionSide),tickerUrl:this.tickerUrl(s),tickerJsonPath:s.tickerJsonPath});this.lastPrice=await this.exchange.getPrice();if(!(this.lastPrice>s.lower&&this.lastPrice<s.upper))throw Error(`当前价格 ${this.lastPrice} 不在网格区间内（当前 ${this.lastPrice}，区间 ${s.lower} - ${s.upper}）`);this.running=true;this.startedAt=Date.now();this._event(`网格已启动：实盘，当前价格 ${this.lastPrice}`);try{const orders=seedOrders({...this.grid,price:this.lastPrice,mode:s.gridMode,skipBand:s.skipBand});for(const order of orders)await this.place(order);}catch(e){await this.stop();this.fail(e);throw e;}this.timer=setInterval(()=>this.tick().catch(e=>this.fail(e)),s.pollMs);this.timer.unref?.();return this.state();}
  async tick(){if(!this.running)return;this.lastPrice=await this.exchange.getPrice();await this.reconcileLive();}
  async reconcileLive(){if(this.config?.mode!=='live'||this.reconcileBusy)return;this.reconcileBusy=true;try{const r=await this.exchange.reconcile();this.officialOrders=r.open;for(const fill of r.fills){const key=String(fill.tradeId||fill.fillId||fill.id||`${fill.orderId||''}:${fill.execTime||fill.timestamp||fill.createdAt||fill.updatedAt||''}:${fill.execPrice||fill.price||fill.orderPrice||''}`);if(this.seenFills.has(key))continue;this.seenFills.add(key);const side=String(fill.side||fill.orderSide||'').toLowerCase().includes('sell')?'sell':'buy';const price=Number(fill.execPrice||fill.price||fill.orderPrice||fill.avgPrice||0);if(!(price>0)){this._event('检测到官方成交但缺少有效成交价，跳过补单，避免错误下单。');continue;}const qty=Number(fill.execQty||fill.qty||fill.quantity||fill.size||fill.orderQty||0);const levelIndex=this.grid.levels.reduce((best,p,i)=>Math.abs(p-price)<Math.abs(this.grid.levels[best]-price)?i:best,0);this.fills.unshift({...fill,side,price,time:Date.now()});this._event(`检测到官方成交：${side==='buy'?'买入':'卖出'} @ ${price}，准备补单（仅内部处理，不发送 TG）`);// 成交只用于内部对账和补单，不发送 Telegram 通知。
      const next=replacementFor({side,levelIndex},this.grid.levels,this.config.gridMode);if(next){const duplicate=[...(this.officialOrders||[]),...[...this.active.values()]].some(o=>{const op=Number(o.price||o.orderPrice||o.avgPrice);const os=String(o.side||o.orderSide||'').toLowerCase().includes('sell')?'sell':'buy';return Number.isFinite(op)&&Math.abs(op-Number(next.price))<1e-8&&os===next.side;});if(!duplicate)await this.place(next);else this._event(`跳过重复补单：${next.side==='buy'?'买':'卖'} @ ${next.price}`);}}this._refreshDerivedPosition();this._persist();}catch(e){this._event(`官方委托同步失败：${e.message}`);this._persist();}finally{this.reconcileBusy=false;}}
  async place(order){if(!this.running)return;const result=await this.exchange.placeOrder({...order,sizeBase:this.config.sizeBase});this.active.set(result.id,{...order,id:result.id,createdAt:Date.now()});this._event(`已确认${order.side==='buy'?'买入':'卖出'}订单：数量 ${this.config.sizeBase}，价格 ${order.price}，交易哈希 ${result.id}`);}
  async replaceOfficialGrid(){if((this.config?.mode||this.settings.mode)!=='live')throw Error('仅实盘支持撤单后重挂');const s=this.settings;if(!this.exchange){this.exchange=new PopdexLiveExchange({rpcUrl:s.rpcUrl,agentPrivateKey:s.agentPrivateKey,mainAccount:s.mainAccount,orderContract:s.orderContract,symbolId:Number(s.symbolId),category:Number(s.category),positionSide:Number(s.positionSide),tickerUrl:this.tickerUrl(s),tickerJsonPath:s.tickerJsonPath,apiToken:s.apiToken,symbol:s.symbol,lotSize:s.lotSize});}if(!this.config){this.config={lower:s.lower,upper:s.upper,gridCount:s.gridCount,sizeBase:s.sizeBase,leverage:s.leverage,gridMode:s.gridMode,skipBand:s.skipBand,pollMs:s.pollMs,mode:'live'};this.grid=buildGrid(this.config);}const current=(await this.exchange.reconcile()).open;const real=current.filter(o=>{const id=String(o?.orderId??o?.id??'');return /^\d+$/.test(id)&&id!=='0';});this._event(`准备撤销官方委托：${real.length} 笔`);for(const order of real){await this.exchange.cancelAndConfirm(order);this._event(`已确认撤销官方订单：${order.orderId??order.id}`);}const price=await this.exchange.getPrice();const orders=seedOrders({...this.grid,price,mode:this.config.gridMode,skipBand:this.config.skipBand});this.running=true;for(const order of orders)await this.place(order);this.running=false;this._event('撤单确认完成，新的网格订单已重新提交。');return this.state();}
  async onFill(fill){if(!this.running)return;this.fills.unshift({...fill,time:Date.now()});if(this.fills.length>50)this.fills.pop();this._event(`Filled ${fill.side.toUpperCase()} ${fill.sizeBase} @ ${fill.price}`);const next=replacementFor(fill,this.grid.levels,this.config.gridMode);if(next)await this.place(next);}
  async stop(){if(this.timer)clearInterval(this.timer);this.timer=null;this.running=false;this.manualStop=true;this._event('网格已停止。注意：已有实盘挂单不会因停止操作自动撤销。');this._persist();return this.state();}
  fail(e){this.error=e?.message||String(e);this._event(`错误：${this.error}`);this._persist();} _event(message){this.log.unshift({time:Date.now(),message});if(this.log.length>80)this.log.pop()}
  state(){const s=this.settings;const liveReady=!!(s.symbol&&s.rpcUrl&&s.agentPrivateKey&&s.mainAccount&&s.orderContract&&s.symbolId!==''&&s.category!==''&&s.positionSide!=='');const publicSettings={...s,agentPrivateKey:'',apiToken:'',rpcUrl:s.rpcUrl||'',mainAccount:s.mainAccount||'',orderContract:s.orderContract||'',agentKeyConfigured:!!s.agentPrivateKey,apiTokenConfigured:!!s.apiToken};const active=[...this.active.values()];const openByLevel={};for(const o of active)if(o.levelIndex!=null)openByLevel[o.levelIndex]=o.side;if(this.grid?.levels?.length&&this.officialOrders?.length){for(const o of this.officialOrders){const price=Number(o.price||o.orderPrice||o.avgPrice||0);if(!(price>0))continue;let best=0;for(let i=1;i<this.grid.levels.length;i++)if(Math.abs(this.grid.levels[i]-price)<Math.abs(this.grid.levels[best]-price))best=i;const side=String(o.side||o.orderSide||'').toLowerCase().includes('sell')?'sell':'buy';openByLevel[best]=side;}}const pos=this.position||null;return {running:this.running,config:this.config,settings:publicSettings,lastPrice:this.lastPrice,grid:this.grid,active,openByLevel,officialOrders:this.officialOrders||[],fills:this.fills,stats:{completedRungs:this.fills.length},log:this.log,error:this.error,startedAt:this.startedAt,liveReady,network:this.env.POPDEX_NETWORK||'mainnet',symbol:s.symbol||null,position:pos,balance:this.exchange?.balance??null,equity:this.exchange?.equity??null,realizedPnl:pos?.realizedPnl??null,unrealizedPnl:pos?.unrealizedPnl??null,totalPnl:(pos?.realizedPnl??0)+(pos?.unrealizedPnl??0),returnPct:null,leverage:s.leverage,liveLimit:'持仓当前由官方成交记录推导；官方账户持仓接口接通后将替换为官方仓位数据。'};}
}


