import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildGrid, seedOrders, replacementFor } from './grid.js';
import { PopdexLiveExchange } from './popdex-live.js';
import { sendTelegram } from './telegram.js';

const officialSide=o=>String(o?.side||o?.orderSide||'').toLowerCase().includes('sell')?'sell':'buy';
const officialPrice=o=>Number(o?.price??o?.orderPrice??o?.avgPrice??0);
const isStrategyOrder=o=>String(o?.clientOid||o?.clientOrderId||o?.clientId||'').startsWith('grid-');
export function strategyAuditPlan({config,grid,price,officialOpen,fills=[],fillAfter=0}){
  const tick=Number(config?.tickSize||1), near=Math.max(tick*.25,1e-8), levels=grid?.levels||[];
  const strategy=(officialOpen||[]).filter(isStrategyOrder), manual=(officialOpen||[]).filter(o=>!isStrategyOrder(o));
  const valid=new Map(), cancel=[];
  for(const order of strategy){const p=officialPrice(order), side=officialSide(order), rounded=Math.round(p/tick)*tick, key=`${rounded}:${side}`;
    const inRange=rounded>=Number(config.lower)-near&&rounded<=Number(config.upper)+near;
    // Live price can cross a resting order before fill propagation. Auto-cancel only objectively malformed bot orders.
    if(!inRange||valid.has(key)){cancel.push(order);continue;}
    valid.set(key,order);
  }
  const placeByKey=new Map();
  const existingPairs=new Set(strategy.map(o=>`${Math.round(officialPrice(o)/tick)*tick}:${officialSide(o)}`));
  for(const fill of fills){const fillTime=Number(fill?.createdAt??fill?.updatedAt??fill?.time??0);if(fillAfter&&!(fillTime>fillAfter))continue;const filledPrice=officialPrice(fill), filledSide=officialSide(fill);if(!(filledPrice>0))continue;const i=levels.reduce((best,p,index)=>Math.abs(p-filledPrice)<Math.abs(levels[best]-filledPrice)?index:best,0);const next=replacementFor({side:filledSide,levelIndex:i},levels,config.gridMode);if(!next)continue;const p=Math.round(Number(next.price)/tick)*tick;if(p<Number(config.lower)-near||p>Number(config.upper)+near)continue;const key=`${p}:${next.side}`;if(!existingPairs.has(key))placeByKey.set(key,{...next,price:p});}
  return {cancel,place:[...placeByKey.values()],manualCount:manual.length,strategyCount:strategy.length};
}

export class GridRunner {
  constructor(env) { this.env=env; this.stateFile=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..','.runtime-state.json'); this.running=false; this.active=new Map(); this.officialOrders=[]; this.fills=[]; this.seenFills=new Set(); this.log=[]; this.timer=null; this.auditTimer=null; this.reconcileBusy=false; this.exchange=null; this.config=null; this.grid=null; this.lastPrice=null; this.startedAt=null; this.lastStrategyAuditAt=0; this.error=null; this.manualStop=false; this.settings=this.makeSettings(); this.restoreState(); }
  _n(k,d){return Number(this.env[k]??d)}
  makeSettings(overrides={}) { const s={mode:'live',lower:this._n('LOWER',90000),upper:this._n('UPPER',110000),gridCount:this._n('GRID_COUNT',20),sizeBase:this._n('ORDER_SIZE_BASE',.0002),lotSize:this._n('POPDEX_LOT_SIZE',.0002),gridMode:this.env.GRID_MODE||'neutral',leverage:this._n('LEVERAGE',1),skipBand:this._n('SKIP_BAND',.25),pollMs:this._n('POLL_MS',1500),apiBase:this.env.POPDEX_API_BASE||'https://api.popdex.xyz',tickerPath:this.env.POPDEX_TICKER_PATH||'/api/v1/public/market/tickers',tickerJsonPath:this.env.POPDEX_TICKER_JSON_PATH||'data.0.lastPrice',apiCategory:this.env.POPDEX_API_CATEGORY||'Futures',symbol:this.env.POPDEX_SYMBOL||'',rpcUrl:this.env.POPDEX_RPC_URL||'https://app.popdex.xyz/api/v1/web3/rpc',agentPrivateKey:this.env.POPDEX_AGENT_PRIVATE_KEY||'',mainAccount:this.env.POPDEX_MAIN_ACCOUNT||'',orderContract:this.env.POPDEX_ORDER_CONTRACT||'0x0000000000000000000000000000000000001000',symbolId:this.env.POPDEX_SYMBOL_ID||'20000',category:this.env.POPDEX_CATEGORY||'2',positionSide:this.env.POPDEX_POSITION_SIDE||'0',apiToken:this.env.POPDEX_API_TOKEN||'',tickSize:this._n('POPDEX_TICK_SIZE',0),...overrides,mode:'live'}; for(const k of ['lower','upper','gridCount','sizeBase','lotSize','skipBand','pollMs','leverage','tickSize'])s[k]=Number(s[k]); delete s.liveTestOnly; if(!(s.tickSize>0)&&String(s.symbol).toUpperCase()==='BTCUSDT')s.tickSize=1; return s; }
  validateSettings(s, requireLive=true){if(s.mode!=='live')throw Error('本脚本仅支持实盘 MODE=live');if(!['neutral','long','short'].includes(s.gridMode))throw Error('网格模式无效');buildGrid(s);if(!(s.sizeBase>0))throw Error('每格数量必须大于 0');if(requireLive){for(const k of ['symbol','rpcUrl','agentPrivateKey','mainAccount','orderContract','symbolId','category','positionSide'])if(s[k]===undefined||s[k]===null||String(s[k]).trim()==='')throw Error(`主网配置缺少：${k}`);}}
  _persist() { const data={version:1,manualStop:this.manualStop,running:this.running,settings:{...this.settings,agentPrivateKey:undefined,apiToken:undefined},config:this.config,lastPrice:this.lastPrice,startedAt:this.startedAt,active:[...this.active.values()],officialOrders:this.officialOrders,fills:this.fills,seenFills:[...this.seenFills],log:this.log.slice(0,80)}; try { fs.writeFileSync(this.stateFile,JSON.stringify(data,null,2),'utf8'); } catch(e) { this.error=`状态保存失败：${e.message}`; } }
  restoreState() { try { if(!fs.existsSync(this.stateFile)) return; const d=JSON.parse(fs.readFileSync(this.stateFile,'utf8')); if(d.settings) this.settings=this.makeSettings(d.settings); this.manualStop=!!d.manualStop; this.config=d.config?{...d.config,mode:'live'}:null; if(this.config)delete this.config.liveTestOnly; this.lastPrice=d.lastPrice??null; this.startedAt=d.startedAt??null; this.officialOrders=Array.isArray(d.officialOrders)?d.officialOrders:[]; this.fills=Array.isArray(d.fills)?d.fills:[]; this.seenFills=new Set(Array.isArray(d.seenFills)?d.seenFills:[]); this.log=Array.isArray(d.log)?d.log:[]; if(this.config)this.grid=buildGrid(this.config); } catch(e) { this.error=`状态恢复失败：${e.message}`; } }
  _restoreExchange() { const s=this.settings; this.exchange=new PopdexLiveExchange({rpcUrl:s.rpcUrl,agentPrivateKey:s.agentPrivateKey,mainAccount:s.mainAccount,orderContract:s.orderContract,symbolId:Number(s.symbolId),category:Number(s.category),positionSide:Number(s.positionSide),tickerUrl:this.tickerUrl(s),tickerJsonPath:s.tickerJsonPath,apiToken:s.apiToken,symbol:s.symbol,lotSize:s.lotSize}); }
  _derivePosition(fills, price) { let qty=0, avg=0, realized=0; for(const f of fills||[]) { const side=String(f.side||f.orderSide||'').toLowerCase().includes('sell')?-1:1; const q=Number(f.execQty||f.qty||f.quantity||f.size||f.orderQty||0), p=Number(f.execPrice||f.price||f.orderPrice||f.avgPrice||0); if(!(q>0&&p>0)) continue; if(qty===0 || Math.sign(qty)===side) { const n=Math.abs(qty)+q; avg=(Math.abs(qty)*avg+q*p)/n; qty+=side*q; } else { const close=Math.min(Math.abs(qty),q); realized += (qty>0 ? (p-avg) : (avg-p))*close; const left=q-close; qty += side*close; if(left>0){qty=side*left;avg=p;} } } if(!qty)return null; const unrealized=(qty>0?(Number(price)-avg):(avg-Number(price)))*Math.abs(qty); return {sizeBase:qty,entryPrice:avg,unrealizedPnl:unrealized,realizedPnl:realized,source:'derived-from-official-fills',warning:'由官方成交记录推导；待接入 PopDEX 官方持仓接口后替换为官方仓位数据'}; }
  _refreshDerivedPosition() { if(this.config?.mode==='live' && this.lastPrice) this.position=this._derivePosition(this.fills,this.lastPrice); }
  syncOfficialStrategyQuantity(orders){const strategy=(orders||[]).filter(isStrategyOrder);const quantities=[...new Set(strategy.map(o=>Number(o?.qty??o?.quantity??o?.orderQty??o?.size??0)).filter(q=>q>0).map(q=>Number(q.toFixed(8))))];if(quantities.length===1&&this.config&&Math.abs(Number(this.config.sizeBase)-quantities[0])>1e-12){const previous=this.config.sizeBase;this.config={...this.config,sizeBase:quantities[0]};this.settings=this.makeSettings({...this.settings,sizeBase:quantities[0]});this._event(`官方策略订单数量与本地草稿不一致：已按官方未成交挂单同步每格数量 ${previous} → ${quantities[0]} BTC。`);return {changed:true,sizeBase:quantities[0]};}return {changed:false,sizeBase:this.config?.sizeBase??null};}
  _notify(text) { sendTelegram(text,this.env).catch(e=>this._event(`Telegram 推送失败：${e.message}`)); }
  async resumeExisting() { if(this.manualStop||this.running||this.settings.mode!=='live'||!this.config)return this.state(); this.validateSettings(this.settings); this._restoreExchange(); const r=await this.exchange.reconcile(); if(!r.open.length){this._event('重启恢复检查：官方无未成交挂单，保持未运行。');this._persist();return this.state();} this.officialOrders=r.open; this.syncOfficialStrategyQuantity(r.open); this.running=true; this.manualStop=false; this.startedAt=Date.now(); this.lastStrategyAuditAt=Date.now(); this._event(`重启自动恢复：接管官方网格 ${r.open.length} 笔，不重新下单；5分钟巡检从本次官方快照开始。`); await this.reconcileLive(); this.timer=setInterval(()=>this.tick().catch(e=>this.fail(e)),this.settings.pollMs); this.timer.unref?.(); this._persist(); return this.state(); }
  async adoptExisting() { if(this.settings.mode!=='live')throw Error('仅实盘支持接管现有官方网格'); if(this.running) return this.state(); this.validateSettings(this.settings); this._restoreExchange(); const r=await this.exchange.reconcile(); if(!r.open.length)throw Error('官方当前没有可接管的未成交挂单'); this.officialOrders=r.open; this.syncOfficialStrategyQuantity(r.open); this.active.clear(); this.running=true; this.manualStop=false; this.error=null; this.lastPrice=await this.exchange.getPrice(); this._event(`手动接管官方网格：${r.open.length} 笔，不重新下单、不撤单。`); await this.reconcileLive(); this.timer=setInterval(()=>this.tick().catch(e=>this.fail(e)),this.settings.pollMs); this.timer.unref?.(); this._persist(); return this.state(); }
  async reconnect() { this._restoreExchange(); const r=await this.exchange.reconcile(); this.officialOrders=r.open; this.lastPrice=await this.exchange.getPrice(); this.error=null; this._event(`交易所已重连并完成只读对账：${r.open.length} 笔官方挂单，未撤单、未平仓、未补单。`); this._persist(); return this.state(); }
  resetStats() { this.error=null; this._event('统计重置请求已记录：保留成交记录、持仓推导和官方挂单，未清除交易数据。'); this._persist(); return this.state(); }
  tickerUrl(s){const base=s.apiBase.replace(/\/$/,'');const qs=new URLSearchParams({category:s.apiCategory,symbol:s.symbol});return `${base}${s.tickerPath}?${qs}`;}
  async resolveOfficialLotSize(s){const meta=await fetch(`${s.apiBase.replace(/\/$/,'')}/api/v1/config/symbols?${new URLSearchParams({category:s.apiCategory})}`,{signal:AbortSignal.timeout(10000)}).then(r=>r.ok?r.json():null).catch(()=>null);const symbol=(meta?.data||[]).find(x=>String(x.symbol).toUpperCase()===String(s.symbol).toUpperCase());const lot=Number(symbol?.lotSize||symbol?.minQty||0);return lot>0?lot:Number(s.lotSize||0.0001);}
  update(overrides={}){if(this.running)throw Error('运行中不可修改配置；请先停止程序');const next=this.makeSettings({...this.settings,...overrides});this.validateSettings(next,false);this.settings=next;this.error=null;this.manualStop=false;this._event('配置已保存，策略尚未启动。');this._persist();return this.state();}  async start(overrides={}){if(this.running)throw Error('网格已经在运行');const cleanOverrides={...overrides};if(!String(cleanOverrides.agentPrivateKey||'').trim())delete cleanOverrides.agentPrivateKey;if(!String(cleanOverrides.mainAccount||'').trim())delete cleanOverrides.mainAccount;if(Object.keys(cleanOverrides).length)this.update(cleanOverrides);const s=this.settings;this.validateSettings(s);const officialLotSize=await this.resolveOfficialLotSize(s);s.lotSize=officialLotSize;if(s.mode==='live'&&s.lotSize>0)s.sizeBase=Number((Math.floor((s.sizeBase+1e-12)/s.lotSize)*s.lotSize).toFixed(8));if(!(s.sizeBase>0))throw Error(`每格数量必须至少为 ${s.lotSize}`);this.config={lower:s.lower,upper:s.upper,gridCount:s.gridCount,sizeBase:s.sizeBase,leverage:s.leverage,gridMode:s.gridMode,skipBand:s.skipBand,pollMs:s.pollMs,tickSize:s.tickSize,mode:s.mode};this.grid=buildGrid(this.config);this.exchange=new PopdexLiveExchange({rpcUrl:s.rpcUrl,agentPrivateKey:s.agentPrivateKey,mainAccount:s.mainAccount,orderContract:s.orderContract,symbolId:Number(s.symbolId),category:Number(s.category),positionSide:Number(s.positionSide),tickerUrl:this.tickerUrl(s),tickerJsonPath:s.tickerJsonPath,lotSize:s.lotSize});this.lastPrice=await this.exchange.getPrice();if(!(this.lastPrice>s.lower&&this.lastPrice<s.upper))throw Error(`当前价格 ${this.lastPrice} 不在网格区间内（当前 ${this.lastPrice}，区间 ${s.lower} - ${s.upper}）`);this.running=true;this.startedAt=Date.now();this._event(`网格已启动：实盘，当前价格 ${this.lastPrice}`);try{const orders=seedOrders({...this.grid,price:this.lastPrice,mode:s.gridMode,skipBand:s.skipBand});for(const order of orders)await this.place(order);}catch(e){await this.stop();this.fail(e);throw e;}this.timer=setInterval(()=>this.tick().catch(e=>this.fail(e)),s.pollMs);this.timer.unref?.();return this.state();}
  async tick(){if(!this.running)return;this.lastPrice=await this.exchange.getPrice();await this.reconcileLive();if(Date.now()-this.lastStrategyAuditAt>=300000)await this.auditStrategyOrders();}
  async reconcileLive(){if(this.config?.mode!=='live'||this.reconcileBusy)return;this.reconcileBusy=true;try{const r=await this.exchange.reconcile();this.officialOrders=r.open;this.active.clear();for(const o of r.open){const id=String(o.orderId??o.id??'');if(isStrategyOrder(o))this.active.set(id,{...o,id,price:officialPrice(o),side:officialSide(o)});}for(const fill of r.fills){const key=String(fill.tradeId||fill.fillId||fill.id||`${fill.orderId||''}:${fill.execTime||fill.timestamp||fill.createdAt||fill.updatedAt||''}:${fill.execPrice||fill.price||fill.orderPrice||''}`);if(this.seenFills.has(key))continue;this.seenFills.add(key);const side=String(fill.side||fill.orderSide||'').toLowerCase().includes('sell')?'sell':'buy';const price=Number(fill.execPrice||fill.price||fill.orderPrice||fill.avgPrice||0);if(!(price>0)){this._event('检测到官方成交但缺少有效成交价，跳过补单，避免错误下单。');continue;}const levelIndex=this.grid.levels.reduce((best,p,i)=>Math.abs(p-price)<Math.abs(this.grid.levels[best]-price)?i:best,0);this.fills.unshift({...fill,side,price,time:Date.now()});this._event(`检测到官方成交：${side==='buy'?'买入':'卖出'} @ ${price}，准备补单（仅内部处理，不发送 TG）`);
      const next=replacementFor({side,levelIndex},this.grid.levels,this.config.gridMode);if(next){const duplicate=(this.officialOrders||[]).filter(isStrategyOrder).some(o=>Math.abs(officialPrice(o)-Number(next.price))<1e-8&&officialSide(o)===next.side);if(!duplicate)await this.place(next);else this._event(`跳过重复补单：${next.side==='buy'?'买':'卖'} @ ${next.price}`);}}this._refreshDerivedPosition();this._persist();}catch(e){this._event(`官方委托同步失败：${e.message}`);this._persist();}finally{this.reconcileBusy=false;}}
  async auditStrategyOrders(){if(!this.running||!this.config)return {ok:true,skipped:'not_running'};if(this.reconcileBusy)return {ok:true,skipped:'reconciliation_busy'};this.reconcileBusy=true;try{const price=await this.exchange.getPrice(),r=await this.exchange.reconcile();this.lastPrice=price;this.officialOrders=r.open;const plan=strategyAuditPlan({config:this.config,grid:this.grid,price,officialOpen:r.open,fills:r.fills,fillAfter:Number(this.startedAt||0)});for(const order of plan.cancel){await this.exchange.cancelAndConfirm(order);this._event(`巡检撤销错误策略单：${officialSide(order)==='buy'?'买':'卖'} @ ${officialPrice(order)}（仅 grid-* 订单）`);}if(plan.cancel.length){const verify=await this.exchange.reconcile();this.officialOrders=verify.open;}for(const order of plan.place)await this.place(order);this.lastStrategyAuditAt=Date.now();this._event(`5分钟官方巡检完成：策略单 ${plan.strategyCount}，撤错单 ${plan.cancel.length}，补缺单 ${plan.place.length}，手工单未触及 ${plan.manualCount}。`);this._persist();return {ok:true,...plan};}catch(e){this.lastStrategyAuditAt=Date.now();this._event(`5分钟官方巡检失败：${e.message}`);this._persist();return {ok:false,error:e.message};}finally{this.reconcileBusy=false;}}
  async place(order){if(!this.running)return;const result=await this.exchange.placeOrder({...order,sizeBase:this.config.sizeBase});this.active.set(result.id,{...order,id:result.id,createdAt:Date.now()});this._event(`已确认${order.side==='buy'?'买入':'卖出'}订单：数量 ${this.config.sizeBase}，价格 ${order.price}，交易哈希 ${result.id}`);}
  async capacityPreview(overrides={}){if(!this.exchange)this._restoreExchange();const official=(await this.exchange.reconcile()).open;const strategy=official.filter(isStrategyOrder);const requestedGridCount=Number(overrides.gridCount??this.config?.gridCount??0);const requestedSize=Number(overrides.sizeBase??this.config?.sizeBase??0);const symbolMeta=await fetch(`${this.settings.apiBase.replace(/\/$/,'')}/api/v1/config/symbols?${new URLSearchParams({category:this.settings.apiCategory})}`,{signal:AbortSignal.timeout(10000)}).then(r=>r.ok?r.json():null).catch(()=>null);const officialSymbol=(symbolMeta?.data||[]).find(x=>String(x.symbol).toUpperCase()===String(this.settings.symbol).toUpperCase());const officialLotSize=Number(officialSymbol?.lotSize||officialSymbol?.minQty||this.settings.lotSize||0.0001);const lot=officialLotSize;const observedQty=strategy.reduce((sum,o)=>sum+Number(o?.qty??o?.quantity??o?.orderQty??o?.size??0),0);const observedCount=strategy.length;const maxSizePerGrid=requestedGridCount>=2&&observedQty>0?Number((Math.floor((observedQty/requestedGridCount+1e-12)/lot)*lot).toFixed(8)):null;const maxGridCount=requestedSize>0&&observedQty>0?Math.floor((observedQty+1e-12)/requestedSize):null;const recommendedSize=maxSizePerGrid&&maxSizePerGrid>=lot?maxSizePerGrid:lot;return {ok:true,source:'official-current-strategy-capacity',observedStrategyOrders:observedCount,observedStrategyQty:Number(observedQty.toFixed(8)),lotSize:lot,requestedGridCount,requestedSize,maxGridCount,maxSizePerGrid,recommendedSize,warning:'基于当前官方策略订单已验证的容量下限计算；账户持仓、可用保证金或交易所风险限额变化时会重新读取，最终仍以交易所回执为准。'};}
  async adjustRange(overrides={}){const lower=Number(overrides.lower),upper=Number(overrides.upper),gridCount=Number(overrides.gridCount??this.config?.gridCount),sizeBase=Number(overrides.sizeBase??this.config?.sizeBase),leverage=Number(overrides.leverage??this.config?.leverage);if(!(Number.isFinite(lower)&&Number.isFinite(upper)&&upper>lower))throw Error('请填写有效的上/下边界');if(!(Number.isInteger(gridCount)&&gridCount>=2))throw Error('网格数量必须为不小于 2 的整数');if(!(sizeBase>0))throw Error('每格数量必须大于 0');if(!(leverage>0))throw Error('杠杆必须大于 0');if(!this.running||!this.config)throw Error('PopDEX 网格未运行，拒绝调整以避免影响非策略订单');const planned={...this.config,lower,upper,gridCount,sizeBase,leverage};buildGrid(planned);return this.replaceOfficialGrid(planned);}
  async rollbackFailedGridAdjustment({previousConfig,previousStrategy,originalError}){const restoreErrors=[];try{const afterFailure=await this.exchange.reconcile();const partial=afterFailure.open.filter(isStrategyOrder);for(const order of partial)await this.exchange.cancelAndConfirm(order);this.officialOrders=(await this.exchange.reconcile()).open;const remaining=this.officialOrders.filter(isStrategyOrder);if(remaining.length)throw Error(`清理失败重建的策略单后仍有 ${remaining.length} 笔`);this.config={...previousConfig};this.grid=buildGrid(this.config);this.running=true;this.active.clear();for(const old of previousStrategy){await this.place({side:officialSide(old),price:officialPrice(old)});}const verified=await this.exchange.reconcile();this.officialOrders=verified.open;const restored=verified.open.filter(isStrategyOrder);if(restored.length!==previousStrategy.length)throw Error(`旧网格恢复数量不一致：预期 ${previousStrategy.length}，实际 ${restored.length}`);this._event(`调整失败已回滚：已清理部分新单并恢复原网格 ${restored.length} 笔。原因：${originalError.message}`);this._persist();return {rolledBack:true,restored:restored.length};}catch(rollbackError){this.running=false;this.manualStop=true;this._event(`调整失败且自动回滚失败：${rollbackError.message}；网格已停止，持仓未处理。原错误：${originalError.message}`);this._persist();throw Error(`调整失败：${originalError.message}；自动回滚也失败：${rollbackError.message}`);}}
  async replaceOfficialGrid(plannedConfig=null){if((this.config?.mode||this.settings.mode)!=='live')throw Error('仅实盘支持撤单后重挂');const s=this.settings;if(!this.exchange)this._restoreExchange();const planned=plannedConfig||this.config||{lower:s.lower,upper:s.upper,gridCount:s.gridCount,sizeBase:s.sizeBase,leverage:s.leverage,gridMode:s.gridMode,skipBand:s.skipBand,pollMs:s.pollMs,tickSize:s.tickSize,mode:'live'};const officialLotSize=await this.resolveOfficialLotSize(this.settings);this.settings=this.makeSettings({...this.settings,lotSize:officialLotSize});this._restoreExchange();const plannedGrid=buildGrid(planned);const price=await this.exchange.getPrice();if(!(price>planned.lower&&price<planned.upper))throw Error(`当前价格 ${price} 不在新网格区间内（${planned.lower} - ${planned.upper}），未撤单`);const current=(await this.exchange.reconcile()).open;const previousConfig={...this.config};const previousStrategy=current.filter(isStrategyOrder);this._event(`调整预检通过：当前价格 ${price}；准备定向撤销官方策略委托 ${previousStrategy.length} 笔。`);for(const order of previousStrategy){await this.exchange.cancelAndConfirm(order);this._event(`已确认撤销官方策略订单：${order.orderId??order.id}`);}this.config=planned;this.grid=plannedGrid;this.officialOrders=[];const orders=seedOrders({...this.grid,price,mode:this.config.gridMode,skipBand:this.config.skipBand});const newlyPlaced=[];try{for(const order of orders){const result=await this.place(order);newlyPlaced.push(result);}this.settings=this.makeSettings({...this.settings,lower:planned.lower,upper:planned.upper,gridCount:planned.gridCount,sizeBase:planned.sizeBase,leverage:planned.leverage});this.running=true;this._event('调整完成：旧策略订单已确认撤销，新的网格订单已重新提交；持仓未处理。');this._persist();return this.state();}catch(originalError){await this.rollbackFailedGridAdjustment({previousConfig,previousStrategy,newlyPlaced,originalError});throw Error(`调整被交易所拒绝，已自动恢复旧网格：${originalError.message}`);}}

  async cancelStrategyOrders(){if(!this.exchange)this._restoreExchange();const official=(await this.exchange.reconcile()).open;const strategy=official.filter(isStrategyOrder),manual=official.filter(o=>!isStrategyOrder(o));if(this.timer)clearInterval(this.timer);this.timer=null;this.running=false;this.manualStop=true;this._event(`撤单预检：官方策略挂单 ${strategy.length} 笔，非策略/手工挂单 ${manual.length} 笔不触及。`);try{for(const order of strategy){await this.exchange.cancelAndConfirm(order);this._event(`已确认撤销策略订单：${order.orderId??order.id}`);}const verified=await this.exchange.reconcile();this.officialOrders=verified.open;const remaining=verified.open.filter(isStrategyOrder);if(remaining.length)throw Error(`官方仍有 ${remaining.length} 笔策略挂单未撤销`);this.active.clear();this.error=null;this._event(`已撤销 ${strategy.length} 笔官方策略挂单；${manual.length} 笔非策略/手工挂单未触及；持仓未处理。`);this._persist();return {ok:true,cancelled:strategy.length,manualUntouched:manual.length,state:this.state()};}catch(e){this.officialOrders=(await this.exchange.reconcile().catch(()=>({open:official}))).open;this._event(`策略撤单中断：${e.message}；网格已停止，未处理持仓。`);this._persist();throw e;}}
  async onFill(fill){if(!this.running)return;this.fills.unshift({...fill,time:Date.now()});if(this.fills.length>50)this.fills.pop();this._event(`Filled ${fill.side.toUpperCase()} ${fill.sizeBase} @ ${fill.price}`);const next=replacementFor(fill,this.grid.levels,this.config.gridMode);if(next)await this.place(next);}
  async stop(){if(this.timer)clearInterval(this.timer);this.timer=null;this.running=false;this.manualStop=true;this._event('网格已停止。注意：已有实盘挂单不会因停止操作自动撤销。');this._persist();return this.state();}
  fail(e){this.error=e?.message||String(e);this._event(`错误：${this.error}`);this._persist();} _event(message){this.log.unshift({time:Date.now(),message});if(this.log.length>80)this.log.pop()}
  state(){const s=this.settings;const liveReady=!!(s.symbol&&s.rpcUrl&&s.agentPrivateKey&&s.mainAccount&&s.orderContract&&s.symbolId!==''&&s.category!==''&&s.positionSide!=='');const publicSettings={...s,agentPrivateKey:'',apiToken:'',rpcUrl:s.rpcUrl||'',mainAccount:s.mainAccount||'',orderContract:s.orderContract||'',agentKeyConfigured:!!s.agentPrivateKey,apiTokenConfigured:!!s.apiToken};const active=[...this.active.values()];const openByLevel={};for(const o of active)if(o.levelIndex!=null)openByLevel[o.levelIndex]=o.side;if(this.grid?.levels?.length&&this.officialOrders?.length){for(const o of this.officialOrders){const price=Number(o.price||o.orderPrice||o.avgPrice||0);if(!(price>0))continue;let best=0;for(let i=1;i<this.grid.levels.length;i++)if(Math.abs(this.grid.levels[i]-price)<Math.abs(this.grid.levels[best]-price))best=i;const side=String(o.side||o.orderSide||'').toLowerCase().includes('sell')?'sell':'buy';openByLevel[best]=side;}}const pos=this.position||null;return {running:this.running,config:this.config,settings:publicSettings,lastPrice:this.lastPrice,grid:this.grid,active,openByLevel,officialOrders:this.officialOrders||[],fills:this.fills,stats:{completedRungs:this.fills.length},log:this.log,error:this.error,startedAt:this.startedAt,liveReady,network:this.env.POPDEX_NETWORK||'mainnet',symbol:s.symbol||null,position:pos,balance:this.exchange?.balance??null,equity:this.exchange?.equity??null,realizedPnl:pos?.realizedPnl??null,unrealizedPnl:pos?.unrealizedPnl??null,totalPnl:(pos?.realizedPnl??0)+(pos?.unrealizedPnl??0),returnPct:null,leverage:s.leverage,liveLimit:'持仓当前由官方成交记录推导；官方账户持仓接口接通后将替换为官方仓位数据。'};}
}


