import fs from 'node:fs'; import http from 'node:http'; import path from 'node:path'; import { execFile } from 'node:child_process'; import { promisify } from 'node:util'; import { fileURLToPath } from 'node:url'; import { GridRunner } from './runner.js'; import { createAgentKey, prepareAgentApproval } from './agent-tools.js'; import { sendTelegram } from './telegram.js'; import { analyzeCandles, combineTrend } from './trend.js';
const execFileAsync=promisify(execFile);
function loadEnv(){if(fs.existsSync('.env'))for(const line of fs.readFileSync('.env','utf8').split(/\r?\n/)){const m=line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2].replace(/^['"]|['"]$/g,'');}}
loadEnv(); const runner=new GridRunner(process.env),root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),port=Number(process.env.PORT||8080),host=process.env.HOST||'0.0.0.0';
setImmediate(()=>{runner.resumeExisting().catch(e=>runner.fail(e));syncAccount().catch(()=>{});});
setInterval(()=>syncAccount().catch(()=>{}),60000).unref?.();
let ai={baseUrl:process.env.AI_BASE_URL||'',apiKey:process.env.AI_API_KEY||'',model:process.env.AI_MODEL||'',intervalMin:Number(process.env.AI_INTERVAL_MIN||5),enabled:false,lastReport:'',lastAt:null,lastError:'',sentinel:null,sentinelError:'',oorAdvice:{},report:null,lastSentinelAt:0,lastReportDate:''};
const json=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));}; const body=req=>new Promise((ok,bad)=>{let d='';req.on('data',x=>d+=x);req.on('end',()=>{try{ok(d?JSON.parse(d):{})}catch{bad(Error('Invalid JSON'))}});});
function popdexHeaders(){const t=runner.settings.apiToken;return t?{Authorization:`Bearer ${t}`,'dy-token':t,Accept:'application/json'}:{Accept:'application/json'};}
async function accountApi(path,query={}){const q=new URLSearchParams(query);const r=await fetch(`https://app.popdex.xyz/web/${path.replace(/^\//,'')}${q.size?'?'+q:''}`,{headers:{...popdexHeaders(),'website':'mix','terminaltype':'1','language':'en','locale':'en','enterPointSource':'web'},signal:AbortSignal.timeout(10000)});const j=await r.json();if(!r.ok||j?.code&&String(j.code)!=='200')throw Error(j?.msg||`账户接口 HTTP ${r.status}`);return j;}
let accountCache={configured:false,source:'popdex-web-api',availableBalance:null,equity:null,lockedMargin:null,volume:null,realizedPnl:null,unrealizedPnl:null,portfolioPnl:null,portfolioPnlSource:null,positions:[],orders:[],error:'尚未请求账户数据',lastUpdated:null};
function accountState(){return {...accountCache,configured:!!runner.settings.apiToken};}
async function portfolioHistory(wallet){
  const r=await fetch(`https://api.popdex.xyz/api/v1/account/${wallet}/history/portfolio`,{headers:{Accept:'application/json','User-Agent':'PopDEX-Grid-Dashboard/1.0'},signal:AbortSignal.timeout(12000)});
  const j=await r.json();
  if(!r.ok||String(j?.code||'200')!=='200')throw Error(j?.msg||`账户组合历史 HTTP ${r.status}`);
  const periods=Array.isArray(j?.data)?j.data:[];
  const alltime=periods.find(x=>String(x?.period||'').toLowerCase()==='alltime')||periods.find(x=>Array.isArray(x?.pnlHistory)&&x.pnlHistory.length);
  const rows=Array.isArray(alltime?.pnlHistory)?alltime.pnlHistory:[];
  const last=rows.filter(x=>Array.isArray(x)&&x.length>=2).slice(-1)[0];
  const pnl=last==null?null:Number(last[1]);
  if(!Number.isFinite(pnl))throw Error('组合历史没有有效 PnL');
  return {pnl,ts:last[0]??null,period:alltime?.period||'Alltime'};
}
function accountData(j){return j?.data??j?.result??j??{};}
function firstNumber(o,keys){for(const k of keys){const v=o?.[k];if(v!==undefined&&v!==null&&v!=='')return v;}return null;}
function collectPositionRows(value,out=[]){if(!value)return out;if(Array.isArray(value)){for(const x of value)collectPositionRows(x,out);return out;}if(typeof value!=='object')return out;const hasQty=['holdQty','holdSize','qty','quantity','positionQty','size','positionSize'].some(k=>value[k]!==undefined&&value[k]!==null&&value[k]!=='');const hasSymbol=['symbol','symbolName','symbolId','market','marketId'].some(k=>value[k]!==undefined&&value[k]!==null&&value[k]!=='');if(hasQty&&hasSymbol)out.push(value);for(const [k,v] of Object.entries(value)){if(k!=='balances'&&k!=='orders'&&k!=='fills')collectPositionRows(v,out);}return out;}
async function syncAccount(){const wallet=runner.settings.mainAccount;if(!wallet)throw Error('未配置主账户地址');const overview=accountData(await accountApi(`v1/account/${wallet}/overview`));let portfolio=null;try{portfolio=await portfolioHistory(wallet);}catch{}let officialPositions=[];try{officialPositions=accountData(await accountApi(`v1/account/${wallet}/positions`));if(!Array.isArray(officialPositions))officialPositions=officialPositions.list||officialPositions.rows||officialPositions.positions||[];}catch{}let orders=[];try{const x=accountData(await accountApi(`v1/account/${wallet}/orders`,{limit:100}));orders=Array.isArray(x)?x:(x.list||x.rows||x.orders||[]);}catch{}let fills=[];try{const x=accountData(await accountApi(`v1/account/${wallet}/trade/fills`,{limit:100,symbol:runner.settings.symbol||'BTCUSDT'}));fills=Array.isArray(x)?x:(x.list||x.rows||x.fills||[]);}catch{}const positions=officialPositions.length?officialPositions:collectPositionRows(overview);const bal=Array.isArray(overview.balances)?overview.balances[0]||{}:{};const accountBalance=firstNumber(bal,['usdValue','balance','equity','available']);const positionUnrealized=positions.reduce((sum,x)=>sum+Number(firstNumber(x,['unPnl','unrealizedPnl','unrealizedProfit','unrealizedProfitLoss','upl'])||0),0);const overviewUnrealized=Number(firstNumber(bal,['upl','unrealizedPnl','unrealizedProfit'])||0);const unrealized=positions.length?positionUnrealized:overviewUnrealized;const accountEquity=accountBalance==null?firstNumber(overview,['accountEquity','equity','totalEquity']):Number(accountBalance)+overviewUnrealized;accountCache={configured:true,source:'popdex-web-api-wallet',availableBalance:accountBalance,equity:accountEquity,lockedMargin:firstNumber(overview,['lockedMargin','locked','marginUsed','frozen','initialMargin']),volume:fills.reduce((sum,x)=>sum+Number(x.execValue||x.value||x.notional||0),0),realizedPnl:portfolio?.pnl!=null?portfolio.pnl-unrealized:null,unrealizedPnl:unrealized,portfolioPnl:portfolio?.pnl??null,portfolioPnlSource:portfolio?`account equity history ${portfolio.period}`:null,positions:positions.map(x=>({symbol:x.symbol||x.symbolName||x.symbolId,side:x.positionSide||x.posSide||x.side,size:x.holdQty||x.holdSize||x.qty||x.quantity||x.positionQty||x.size||x.positionSize||'0',entry:x.avgOpenPrice||x.entryPrice||x.avgPrice||x.averageEntryPrice||'0',pnl:x.unPnl||x.unrealizedPnl||x.unrealizedProfit||x.unrealizedProfitLoss||x.upl||'0',markPrice:x.markPrice||x.mark||x.indexPrice||null})),orders:orders.map(x=>({id:x.orderId||x.id,symbol:x.symbol||x.symbolId,side:x.side,status:x.status,price:x.price||x.orderPrice,qty:x.qty||x.quantity||x.orderQty})),error:null,lastUpdated:Date.now()};return accountCache;}
function aiPublic(){return {...ai,apiKey:ai.apiKey?'configured (hidden)':''};} function state(){return {...runner.state(),account:accountState(),ai:aiPublic()};}
const AI_ENV_KEYS=new Set(['AI_PROVIDER','AI_BASE_URL','AI_API_KEY','AI_MODEL','AI_MODEL_SMALL','AI_SENTINEL_MINUTES','AI_REPORT_HOUR','TELEGRAM_BOT_TOKEN','TELEGRAM_CHAT_ID','NOTIFY_WEBHOOK','AI_TG_TOKEN','AI_TG_CHAT','AI_WEBHOOK','GLOBAL_PROXY','DECIBEL_PROXY','EXTENDED_PROXY','RISEX_PROXY']);
function envValue(key){return process.env[key]||'';}
function aiStatus(){const provider=envValue('AI_PROVIDER')||((ai.baseUrl||'').includes('anthropic')?'anthropic':(ai.baseUrl||'').includes('generativelanguage')?'gemini':'openai');return {configured:!!(envValue('AI_API_KEY')||ai.apiKey),provider,baseUrl:envValue('AI_BASE_URL')||ai.baseUrl,model:envValue('AI_MODEL')||ai.model,modelSmall:envValue('AI_MODEL_SMALL'),sentinelMin:Number(envValue('AI_SENTINEL_MINUTES')||5),reportHour:Number(envValue('AI_REPORT_HOUR')||0),apiKeyMasked:envValue('AI_API_KEY')||ai.apiKey?'已配置':'',telegramTokenMasked:envValue('TELEGRAM_BOT_TOKEN')?'已配置':'',telegramChat:envValue('TELEGRAM_CHAT_ID'),webhook:envValue('NOTIFY_WEBHOOK'),notifyChannels:[...(envValue('TELEGRAM_BOT_TOKEN')&&envValue('TELEGRAM_CHAT_ID')?['Telegram']:[]),...(envValue('NOTIFY_WEBHOOK')?['Webhook']:[])],sentinel:ai.sentinel,sentinelError:ai.sentinelError,report:ai.report,oorAdvice:ai.oorAdvice};}
async function runSentinel(){const s=runner.state(), problems=[];if(!s.running)problems.push('PopDEX 网格当前未运行');if(s.running&&!s.officialOrders?.length)problems.push('PopDEX 运行中但未读取到官方挂单');if(s.lastPrice!=null&&(s.lastPrice<s.settings.lower||s.lastPrice>s.settings.upper))problems.push(`PopDEX 价格 ${s.lastPrice} 已超出网格区间 ${s.settings.lower}~${s.settings.upper}`);let ondo;try{ondo=await ondoAiSnapshot();if(ondo.gridRunning&&ondo.openStrategyOrders===0)problems.push('Ondo 显示运行中但未读到策略挂单');if(ondo.configuredRange&&ondo.gridRunning&&ondo.availableMargin!=null&&Number(ondo.availableMargin)<=0)problems.push('Ondo 可用保证金为零或不可用');}catch(e){problems.push(`Ondo 状态读取失败：${e.message}`)}const level=problems.length?'warn':'ok';let summary=problems.length?problems.join('；'):`PopDEX 与 Ondo 网格状态、官方挂单和区间检查正常${ondo?`；Ondo 策略挂单 ${ondo.openStrategyOrders}`:''}`;let advice='',ondoAdvice='';if(aiStatus().configured){try{advice=await askAi(`请检查以下 PopDEX 只读交易状态，输出风险等级、运行/持仓/挂单事实、区间或趋势风险、保证金或杠杆风险、3条明确建议。严禁交易操作。数据：${JSON.stringify({running:s.running,symbol:s.symbol,price:s.lastPrice,range:[s.settings.lower,s.settings.upper],officialOrders:s.officialOrders?.length,fills:s.fills?.length,position:s.position})}`);if(ondo)ondoAdvice=await askAi(`你是 Ondo Perp 网格的只读 AI 哨兵。请只根据以下 Ondo 数据输出与 PopDEX 卡片同等篇幅的精简中文报告，严格不超过 650 个中文字符、不使用 Markdown 表格、不重复数据、不执行交易。格式固定为：\n风险等级：低/中/高 + 一句总评\n当前状态：市场、现价、持仓/均价/未实现盈亏、挂单数、区间/格数/杠杆、可用保证金（合并为1-2行）\n趋势与风险：15m/1h/4h结论、区间边界和杠杆风险（2-3条）\n建议：仅3条简短只读风控建议。\n数据：${JSON.stringify(ondo)}`);summary += `\nAI建议：${advice}`;}catch(e){ai.sentinelError=e.message;}}const ondoEvidence=ondo?`策略状态：${ondo.gridRunning?'运行中':'未运行'}；官方策略挂单：${ondo.openStrategyOrders}；市场：${ondo.market}；可用保证金：${ondo.availableMargin??'—'}。${problems.filter(x=>x.includes('Ondo')).join('；')||'检查正常'}`:'Ondo 数据不可用';ai.sentinel={t:Date.now(),level,summary,per:{de:{level,summary},ondo:{level,summary:`${ondoEvidence}${ondoAdvice?`\nAI 哨兵分析：${ondoAdvice}`:''}`}}};ai.lastSentinelAt=Date.now();if(level!=='ok')sendTelegram(`🛡 网格风控哨兵\n${summary}`).catch(()=>{});return ai.sentinel;}
async function runReport(){const s=runner.state(),ondo=await ondoAiSnapshot().catch(e=>({error:e.message}));const text=await askAi(`请生成 PopDEX 与 Ondo Perp 网格运行复盘日报，分别包含运行状态、官方挂单数、成交/持仓、价格或市场、参数和风险提示。只读分析，不执行交易。数据：${JSON.stringify({popdex:{running:s.running,symbol:s.symbol,price:s.lastPrice,orders:s.officialOrders?.length,fills:s.fills?.length,position:s.position,config:s.config},ondo})}`);ai.report={t:Date.now(),text};await sendTelegram(`📋 PopDEX + Ondo 网格运行复盘日报\n${text}`).catch(()=>{});return ai.report;}
setInterval(()=>{const n=Number(envValue('AI_SENTINEL_MINUTES')||0);if(n>0&&Date.now()-ai.lastSentinelAt>=n*60000)runSentinel().catch(e=>{ai.sentinelError=e.message});const h=Number(envValue('AI_REPORT_HOUR')||-1),now=new Date(),date=now.toISOString().slice(0,10);if(h>=0&&now.getHours()===h&&ai.lastReportDate!==date){ai.lastReportDate=date;runReport().catch(e=>{ai.lastError=e.message});}},60000).unref?.();
function persistEnv(key,value){if(!AI_ENV_KEYS.has(key))throw Error('不允许修改该配置项');const file=path.join(process.cwd(),'.env');let lines=fs.existsSync(file)?fs.readFileSync(file,'utf8').split(/\r?\n/):[];let found=false;lines=lines.map(line=>{if(line.match(new RegExp('^\\s*'+key.replace(/[.*+?^${}()|[\\]\\\\]/g,'\\\\$&')+'\\s*='))){found=true;return `${key}=${value}`;}return line;});if(!found)lines.push(`${key}=${value}`);fs.writeFileSync(file,lines.filter((x,i,a)=>i<a.length-1||x!=='').join('\n')+'\n',{mode:0o600});process.env[key]=value;if(key==='AI_BASE_URL')ai.baseUrl=value;if(key==='AI_API_KEY')ai.apiKey=value;if(key==='AI_MODEL')ai.model=value;return aiStatus();}
function proxyStatus(){return {global:envValue('GLOBAL_PROXY'),de:envValue('DECIBEL_PROXY'),ex:envValue('EXTENDED_PROXY'),rs:envValue('RISEX_PROXY')};}
async function proxyCheck(){const proxy=envValue('GLOBAL_PROXY')||envValue('DECIBEL_PROXY')||envValue('EXTENDED_PROXY')||envValue('RISEX_PROXY');if(!proxy)return {ok:false,configured:false,error:'未配置代理，当前为直连模式'};try{const {stdout}=await execFileAsync('curl',['--proxy',proxy,'--connect-timeout','8','--max-time','15','-fsS','https://api.ipify.org?format=json'],{timeout:18000,maxBuffer:4096});const j=JSON.parse(stdout);return {ok:true,configured:true,ip:j.ip||stdout.trim()};}catch(e){return {ok:false,configured:true,error:'代理连接失败，请检查代理地址、协议和账号密码'};}}
function decimalPlaces(v){const s=String(v??'');if(!s.includes('.'))return 0;return s.split('.')[1].replace(/0+$/,'').length;}
async function validateOrder(b){const symbol=String(b.symbol||runner.settings.symbol||'BTCUSDT').toUpperCase();const category=String(b.category||runner.settings.apiCategory||'Futures');const metaRes=await fetch(`${runner.settings.apiBase.replace(/\/$/,'')}/api/v1/config/symbols?${new URLSearchParams({category})}`);const metaJson=await metaRes.json();const meta=(metaJson.data||[]).find(x=>String(x.symbol).toUpperCase()===symbol);if(!meta)throw Error(`找不到交易对 ${symbol}`);const tickerRes=await fetch(`${runner.settings.apiBase.replace(/\/$/,'')}/api/v1/public/market/tickers?${new URLSearchParams({category,symbol})}`);const ticker=(await tickerRes.json()).data?.[0];const price=Number(b.price||ticker?.bid1Price||ticker?.lastPrice);const qty=Number(b.qty);if(!(price>0&&qty>0))throw Error('价格和数量必须大于 0');const lot=Number(meta.lotSize||meta.minQty||'0.0001'),minQty=Number(meta.minQty||lot),minNotional=Number(meta.minNotional||10);if(qty<minQty||qty/lot%1>1e-8)throw Error(`数量不符合最小数量/步长：${meta.minQty||lot}`);if(price*qty<minNotional)throw Error(`名义金额 ${price*qty.toFixed(2)} 小于最低 ${minNotional}`);const side=String(b.side||'Buy');const canonical={symbolId:String(meta.symbolId),symbol,category,side,orderType:'NORMAL',priceType:'LIMIT',price:String(b.price),qty:String(b.qty),timeInForce:'GTC',positionSide:String(b.positionSide||'LONG'),reduceOnly:Boolean(b.reduceOnly||false),leverage:String(b.leverage||'1'),marginMode:String(b.marginMode||'cross'),languageType:'en',enterPointSource:'WEB'};return {ok:true,sent:false,endpoint:'/web/v1/uta/order/place',market:{lastPrice:ticker?.lastPrice||null,bid1Price:ticker?.bid1Price||null,ask1Price:ticker?.ask1Price||null},checks:{lotSize:lot,minQty,minNotional,notional:Number((price*qty).toFixed(8)),balance:accountState().availableBalance},payload:canonical,warning:'仅生成并校验，未发送真实请求'};}
async function candles(interval='15m',limit='120',symbolOverride='',categoryOverride=''){const symbol=String(symbolOverride||runner.settings.symbol||'').trim();if(!symbol)return [];const category=categoryOverride||runner.settings.apiCategory||'Futures';const q=new URLSearchParams({category,symbol,interval,type:'Market',limit});const r=await fetch(`${runner.settings.apiBase.replace(/\/$/,'')}/api/v1/public/market/candles?${q}`);const j=await r.json();if(!r.ok||String(j.code||'200')!=='200')throw Error(j.msg||`行情接口 HTTP ${r.status}`);return (j.data||[]).slice(-60).map(x=>({time:Number(x.time??x[0]),open:Number(x.open??x[1]),high:Number(x.high??x[2]),low:Number(x.low??x[3]),close:Number(x.close??x[4])})).filter(x=>[x.time,x.open,x.high,x.low,x.close].every(Number.isFinite));}
async function trendAnalysis(symbol,category){const frames=await Promise.all([['15m','120'],['1H','120'],['4H','120']].map(([i,l])=>candles(i,l,symbol,category)));return combineTrend(frames.map(analyzeCandles));}
async function askAi(prompt){if(!ai.baseUrl||!ai.apiKey||!ai.model)throw Error('请先在 AI 助手页填写 API Base URL、API Key 和模型');const base=ai.baseUrl.replace(/\/$/,'').replace(/\/chat\/completions$/,'');const r=await fetch(`${base}/chat/completions`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${ai.apiKey}`},body:JSON.stringify({model:ai.model,temperature:.2,messages:[{role:'system',content:'你是交易网格策略分析助手。只分析和提示风险，不调用交易接口、不下单、不撤单、不修改杠杆，也不承诺收益。用简体中文，输出简洁且结构化。'},{role:'user',content:prompt}]})});const j=await r.json();if(!r.ok)throw Error(j?.error?.message||j?.message||`AI HTTP ${r.status}`);return j?.choices?.[0]?.message?.content||JSON.stringify(j);}
async function ondoAiSnapshot(){const [overview, candles15, candles1h, candles4h]=await Promise.all([fetch('http://127.0.0.1:8020/api/overview',{signal:AbortSignal.timeout(12000)}).then(r=>r.json()),fetch('http://127.0.0.1:8020/api/candles?market=BTC-USD.P&interval=15m&limit=60',{signal:AbortSignal.timeout(12000)}).then(r=>r.json()),fetch('http://127.0.0.1:8020/api/candles?market=BTC-USD.P&interval=1h&limit=60',{signal:AbortSignal.timeout(12000)}).then(r=>r.json()),fetch('http://127.0.0.1:8020/api/candles?market=BTC-USD.P&interval=4h&limit=60',{signal:AbortSignal.timeout(12000)}).then(r=>r.json())]);const o=overview.ondo||overview,live=o.live||{},orders=o.orders||[];return {venue:'Ondo Perp',market:live.config?.market||'BTC-USD.P',gridRunning:!!live.running,configuredRange:live.config?{lower:live.config.lower,upper:live.config.upper,gridCount:live.config.gridCount,size:live.config.size,leverage:live.config.leverage,mode:live.config.mode}:null,openStrategyOrders:orders.filter(x=>x.status==='open'&&String(x.clientOrderId||'').startsWith('hermes_')).length,positions:o.positions||[],availableMargin:o.balance?.availableMargin,frames:{'15m':(candles15.candles||[]).slice(-30),'1h':(candles1h.candles||[]).slice(-30),'4h':(candles4h.candles||[]).slice(-30)}};}
async function ondoAiAnalyze(){const snapshot=await ondoAiSnapshot();const report=await askAi(`请对 Ondo Perp 网格做只读分析。给出：1) 15m/1h/4h趋势；2) 当前是否适合网格；3) 若现有策略在运行，检查区间、网格数、杠杆和保证金的风险；4) 三条明确风险提示；5) 仅建议参数，不执行任何操作。\n数据=${JSON.stringify(snapshot)}`);return {report,snapshot};}
async function ondoTrendAnalysis(market='BTC-USD.P'){const base='http://127.0.0.1:8020/api/candles?';const frames=await Promise.all(['15m','1h','4h'].map(async interval=>{const q=new URLSearchParams({market,interval,limit:'120'});const r=await fetch(base+q,{signal:AbortSignal.timeout(15000)});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||`${interval} K线读取失败`);return j.candles||[];}));return combineTrend(frames.map(analyzeCandles));}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://127.0.0.1');try{
if(url.pathname==='/api/state')return json(res,200,state());
if(url.pathname==='/api/ondo/overview'){
  const r=await fetch('http://127.0.0.1:8020/api/overview',{signal:AbortSignal.timeout(10000)});
  const j=await r.json();
  return json(res,r.status,j);
}
if(url.pathname==='/api/ondo/markets'){
  const r=await fetch('http://127.0.0.1:8020/api/markets',{signal:AbortSignal.timeout(15000)});
  return json(res,r.status,await r.json());
}
if(url.pathname==='/api/ondo/candles'){
  const q=new URLSearchParams({market:url.searchParams.get('market')||'BTC-USD.P',interval:url.searchParams.get('interval')||'1h',limit:url.searchParams.get('limit')||'120'});
  const r=await fetch(`http://127.0.0.1:8020/api/candles?${q}`,{signal:AbortSignal.timeout(15000)});
  return json(res,r.status,await r.json());
}
if(url.pathname==='/api/ondo/trend'){const market=url.searchParams.get('market')||'BTC-USD.P';return json(res,200,{ok:true,analysis:await ondoTrendAnalysis(market)});}
if(url.pathname==='/api/ondo/live/adjust'&&req.method==='POST'){const b=await body(req);const r=await fetch('http://127.0.0.1:8020/api/live/adjust',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b),signal:AbortSignal.timeout(120000)});return json(res,r.status,await r.json());}
if(url.pathname==='/api/ondo/live/start'&&req.method==='POST'){const b=await body(req);const r=await fetch('http://127.0.0.1:8020/api/live/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b),signal:AbortSignal.timeout(90000)});return json(res,r.status,await r.json());}
if(url.pathname==='/api/ondo/live/stop'&&req.method==='POST'){const r=await fetch('http://127.0.0.1:8020/api/live/stop',{method:'POST',signal:AbortSignal.timeout(30000)});return json(res,r.status,await r.json());}
if(url.pathname==='/api/ondo/live/cancel'&&req.method==='POST'){const b=await body(req);const market=encodeURIComponent(String(b.market||''));const r=await fetch(`http://127.0.0.1:8020/api/live/cancel?market=${market}`,{method:'POST',signal:AbortSignal.timeout(30000)});return json(res,r.status,await r.json());}
if(url.pathname==='/api/account'){return json(res,200,accountState());}
if(url.pathname==='/api/account/sync'&&req.method==='POST'){try{return json(res,200,{ok:true,data:await syncAccount()});}catch(e){accountCache={...accountCache,error:e?.message||String(e),lastUpdated:Date.now()};return json(res,400,{ok:false,error:accountCache.error,data:accountState()});}}
if(url.pathname==='/api/account/test'&&req.method==='POST'){const wallet=runner.settings.mainAccount;if(!wallet)throw Error('请先保存主账户地址');const j=await accountApi(`v1/account/${wallet}/status`);return json(res,200,{ok:true,data:j.data||j});}
if(url.pathname==='/api/symbols'){const q=new URLSearchParams({category:url.searchParams.get('category')||'Futures'});const rr=await fetch(`${runner.settings.apiBase.replace(/\/$/,'')}/api/v1/config/symbols?${q}`);return json(res,rr.status,await rr.json());}
if(url.pathname==='/api/candles'){const symbol=url.searchParams.get('symbol')||'';const category=url.searchParams.get('category')||'Futures';return json(res,200,{code:'200',data:await candles(url.searchParams.get('interval')||'1m',url.searchParams.get('limit')||'120',symbol,category)});}
if(url.pathname==='/api/trend'){const symbol=url.searchParams.get('symbol')||runner.settings.symbol||'';const category=url.searchParams.get('category')||runner.settings.apiCategory||'Futures';return json(res,200,{analysis:await trendAnalysis(symbol,category)});}
if(url.pathname==='/api/order/validate'&&req.method==='POST')return json(res,200,await validateOrder(await body(req)));
if(url.pathname==='/api/agent/create'&&req.method==='POST')return json(res,200,createAgentKey());
if(url.pathname==='/api/agent/prepare-approval'&&req.method==='POST')return json(res,200,prepareAgentApproval(await body(req)));
if(url.pathname==='/api/config'&&req.method==='POST')return json(res,200,runner.update(await body(req)));
if(url.pathname==='/api/start'&&req.method==='POST')return json(res,200,await runner.start(await body(req)));
if(url.pathname==='/api/adopt-existing'&&req.method==='POST')return json(res,200,await runner.adoptExisting());
if(url.pathname==='/api/stop'&&req.method==='POST')return json(res,200,await runner.stop());
if(url.pathname==='/api/replace-grid'&&req.method==='POST')return json(res,200,await runner.replaceOfficialGrid());
if(url.pathname==='/api/capacity-preview'&&req.method==='POST')return json(res,200,await runner.capacityPreview(await body(req)));
if(url.pathname==='/api/adjust'&&req.method==='POST')return json(res,200,await runner.adjustRange(await body(req)));
if(url.pathname==='/api/cancel-orders'&&req.method==='POST')return json(res,200,await runner.cancelStrategyOrders());
if(url.pathname==='/api/env'&&req.method==='POST'){const b=await body(req);return json(res,200,{ok:true,data:persistEnv(String(b.key||''),String(b.value??''))});}
if(url.pathname==='/api/de/reset'&&req.method==='POST')return json(res,200,{ok:true,data:runner.resetStats()});
if(url.pathname==='/api/de/reconnect'&&req.method==='POST')return json(res,200,{ok:true,data:await runner.reconnect()});
if(url.pathname==='/api/proxy-config')return json(res,200,proxyStatus());
if(url.pathname==='/api/proxy-check')return json(res,200,await proxyCheck());
if(url.pathname==='/api/ai/status')return json(res,200,aiStatus());
if(url.pathname==='/api/telegram/test'&&req.method==='POST'){const result=await sendTelegram('✅ PopDEX Telegram 通知测试成功。');return json(res,200,result);}
if(url.pathname==='/api/ai/sentinel-run'&&req.method==='POST')return json(res,200,{ok:true,sentinel:await runSentinel()});
if(url.pathname==='/api/ai/report'&&req.method==='POST')return json(res,200,{ok:true,report:await runReport()});
if(url.pathname==='/api/ai/config'&&req.method==='POST'){const b=await body(req);for(const k of ['baseUrl','model','intervalMin','enabled'])if(b[k]!==undefined)ai[k]=b[k];if(b.apiKey)ai.apiKey=b.apiKey;return json(res,200,aiPublic());}
if(url.pathname==='/api/ai/test'&&req.method==='POST'){const started=Date.now();const report=await askAi('请仅回复“连接成功”。');return json(res,200,{ok:true,provider:aiStatus().provider,model:ai.model,ms:Date.now()-started,reply:report});}
if(url.pathname==='/api/ai/analyze'&&req.method==='POST'){const b=await body(req);if(String(b.ex||'').toLowerCase()==='ondo'){const result=await ondoAiAnalyze();ai.lastReport=result.report;ai.lastAt=Date.now();ai.lastError='';return json(res,200,{report:result.report,at:ai.lastAt,venue:'ondo',snapshot:result.snapshot});}const s=runner.state(),k=await candles('15m','60');const report=await askAi(`请分析以下 PopDEX 网格机器人状态，并给出：趋势判断、当前网格适配性、三条风险提示、建议参数范围。\n状态=${JSON.stringify({symbol:s.symbol,lastPrice:s.lastPrice,config:s.config,active:s.active,position:s.position})}\n近60根15mK线=${JSON.stringify(k)}`);ai.lastReport=report;ai.lastAt=Date.now();ai.lastError='';return json(res,200,{report,at:ai.lastAt,venue:'popdex'});}
if(url.pathname==='/'||url.pathname==='/index.html'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});return fs.createReadStream(path.join(root,'public','index.html')).pipe(res);} return json(res,404,{error:'Not found'});
}catch(e){if(url.pathname.startsWith('/api/ai/'))ai.lastError=e?.message||String(e);return json(res,400,{error:e?.message||String(e),state:state()});}});
server.listen(port,host,()=>console.log(`PopDEX Grid Dashboard: http://${host}:${port}`));
